### ISSUE TITLE
pip install doesn't work on ubuntu

### ISSUE THREAD

**Issue by Th3-Think3r** [jamesacampbell/spry#5]
pip3 does though. Maybe its just because I only have that version enabled?

Also cloning via git clone did not allow the tool to run as suggested in the instructions. pip3 install did

**Comment by james-see** [comment]
Yes, this is a python 3 only repo, so if your pip command points to 2.7x then it will not work. This is correct behavior. What did you do when you cloned it? You should run `python3 install setup.py`

**Comment by james-see** [comment]
Closing this, please open again if you would like to explain further what your issue is. Cheers
